### ISSUE TITLE
Remove or populate 'Visualize' section on landing page.

### ISSUE THREAD

**Issue by DennisSchwartz** [biojs/biojs-frontend#35]
The 'Visualize' section of the landing page is empty.
If it can't be populated by the end of the week, let's remove it for now.

**Comment by sarthak-sehgal** [comment]
@DennisSchwartz I can add the contents to it but since the visualizations take time to load and sometimes don't even load, should we have that section?
I remember having this conversation with @rowlandm during the application period and he said that since visualizations are a core part of BioJS, we need to have it. If that's the case, can we just get the bundled JS for Cytoscape and serve it? The UX will be really good then. What do you think @Megh-Thakkar @rowlandm?

**Comment by sarthak-sehgal** [comment]
Which component shall we display on the home page then?

**Comment by rowlandm** [comment]
Good question. I dont have the answer to that.

**Comment by yochannah** [comment]
how about https://www.npmjs.com/package/ProtVista ?

**Comment by rowlandm** [comment]
I can't seem to see it working:
http://139.59.93.32/biojs-frontend/dist/#/component/protvista
or
http://biojs.io/d/ProtVista


What about bio-pv? Just found it at random....
http://139.59.93.32/biojs-frontend/dist/?#/component/bio-pv

**Comment by sarthak-sehgal** [comment]
bio-pv looks good!

**Comment by rowlandm** [comment]
Cool.

Sarthak - if you can confirm protvista isn't working at the moment, can you
use bio-pv as a default please?

I want us to copy over the javascript into our repo so that it isn't
relying on the npm and will always work for the front end. It also has to
be fast-ish.

Is that OK?

Later on, we can always change to another visualisation.

**Comment by sarthak-sehgal** [comment]
The visualization for ProtVista seems to be buggy.
I'll incorporate bio-pv on the landing page by hosting the bundle files and the dependencies statically.
As Rowland pointed out, we can change the component anytime!

**Comment by rowlandm** [comment]
Excellent

**Comment by rowlandm** [comment]
Looks good - question if we can replace the black mobile phone to the right of the "Welcome to BioJS" with the visualisation of bio-pv.

**Comment by rowlandm** [comment]
Can we have a link to bio-pv on the frontpage to the component please?

http://139.59.93.32/biojs-frontend/dist/#/component/bio-pv

**Comment by sarthak-sehgal** [comment]
@rowlandm, I can replace the mobile phone but the visualization won't load as soon as the home page loads which might lead to a poorer UX.

**Comment by rowlandm** [comment]
Good point. Leave it alone! :)
